apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskappdeploy
  labels:
    app: nagaapp  # This should match the selector and template labels
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nagaapp
  template:
    metadata:
      labels:
        app: nagaapp
    spec:
      containers:
        - name: flaskappcontainer
          image: nagarjunaboddupalli/nagaapp
          ports:
            - containerPort:5000
