apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_app-deploy
  labels:
    app: flask_app  # This should match the selector and template labels
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask_app
  template:
    metadata:
      labels:
        app: flask_app
    spec:
      containers:
        - name: flask_app-container
          image: nagarjunaboddupalli/flask_demo
          ports:
            - containerPort: 8888