apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaappdeploy
  labels:
    app: myjavaapp  # This should match the selector and template labels
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: myjavaapp-container  # Added space after colon for readability
          image: nagarjunaboddupalli/myjavaapp
          ports:
            - containerPort: 8080  # Added space after colon for consistency
