apiVersion: v1  # Specify the API version
kind: Service   # Specify the Kubernetes resource kind

metadata:
  name: myapp-svc  # Name of the Service
  labels:
    app: myapp 
    version: 2.6.2    # Labels associated with the Service

spec:
  type: NodePort   # Type of the Service (NodePort in this case)
  ports:
    - port: 8080   # Port exposed by the Service
      nodePort: 30001  # NodePort to be used (typo corrected here from 'nodeport' to 'nodePort')
      protocol: TCP  # Protocol used for the port (typo corrected here from 'protocall' to 'protocol')
  selector:
    app: myapp  
    version: 2.6.2   # Selector to match Pods targeted by this Service
