apiVersion: v1
kind: Service
metadata:
  name: flask_appp-svc
  labels: 
    app: flask_app  # Specify a value for the 'app' label
spec:
  type: NodePort
  ports:
    - port: 8888   # This is the port your service listens on internally
      targetPort: 8888  # This is the port your application listens on
      nodePort: 30002
      protocol: TCP  # Use a different available NodePort, like 30002
  selector:
    app: flask_app   # Make sure this selector matches your deployment or pods
