apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels: 
    app: myjavaapp  # This label helps to select the correct pods
spec:
  type: NodePort
  ports:
    - port: 8080        # The port the service exposes internally
      targetPort: 8080  # The port the application listens on inside the Pod
      nodePort: 30001   # External port on the node (range: 30000-32767)
      protocol: TCP
  selector:
    app: myjavaapp  # This should match the labels used in the Deployment or Pods
