apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
spec:
  type: NodePort
  ports:
    - port: 8080   # This is the port your service listens on internally
      targetPort: 8080  # This is the port your application listens on
      nodePort: 30002  # Use a different available NodePort, like 30002
  selector:
    app: myjavaapp   # Make sure this selector matches your deployment or pods
