apiVersion: v1
kind: Service
metadata:
  name: flaskapppsvc
  labels: 
    app: nagaapp  # This label helps to select the correct pods
spec:
  type: NodePort
  ports:
    - port: 50000   # This is the port the service exposes internally
      targetPort: 50000  # This is the port the application listens on
      nodePort: 30002  # Ensure this is within the valid range (30000-32767)
      protocol: TCP
  selector:
    app: nagaapp  # This should match the labels used in the Deployment or Pods
